### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by patpatpat123** [mike-neck/rsocket-swift#1]
Hello Mike,

Thank you for putting this up.
I was wondering, is this project still maintained?

I think the concept on reactive stream and rocket for swift is more than interesting.
Thank you

**Comment by mike-neck** [comment]
This project has not been maintained recently. But more seriously, the project is not completed.

**Comment by patpatpat123** [comment]
Thank you for your comment and input.

May I ask what are the remaining tasks please?
And two years after your last commit, with SwiftNIO mainstreamed, what are the new possibilities?

Thank you

**Comment by mike-neck** [comment]
There are so many many tasks that I can't list them any more.
If you would like to use RSocket on Swift, I will recommend you to implement them in your own.

**Comment by patpatpat123** [comment]
Understood Mike, thanks!
